

no_document use_thys
   ["Atoms",
    "Eqvt",
    "Ex/Weakening",
    "Ex/Classical",
    "Ex/Datatypes",
    "Ex/Ex1",
    "Ex/ExPS3",
    "Ex/Multi_Recs",
    "Ex/Multi_Recs2",
    "Ex/LF",
    "Ex/Lambda",
    (*"Ex/Let",*)
    "Ex/LetPat",
    "Ex/LetRec",
    "Ex/LetRec2",
    "Ex/LetFun",
    "Ex/Modules",
    "Ex/SingleLet",
    "Ex/Shallow",
    "Ex/SystemFOmega",
    "Ex/TypeSchemes1",
    "Ex/TypeSchemes2",
    "Ex/TypeVarsTest",
    "Ex/Foo1",
    "Ex/Foo2",
    "Ex/CoreHaskell",
    "Ex/CoreHaskell2",
    "Ex/Pi",
    "Ex/Local_Contexts"
   ];

quick_and_dirty := true;

no_document use_thys
   ["Ex/Let"];


